### ISSUE TITLE
UnassignedReferenceException: _downsample1Compute not assigned

### ISSUE THREAD

**Issue by demonixis** [keijiro/MiniEngineAO#2]
Hello,

When I use the last sources I have this error message 

![image](https://user-images.githubusercontent.com/1017126/29071573-814d173e-7c44-11e7-9b8c-e1f8fe1fc6c3.png)

I tried on an empty scene, I don't have any messages, but I can't see the AO.

I tested this issue on two configurations
- GeForce GTX 980 Windows 10 Creator Update
- RX 480 8Gb - Windows 10 Fast Ring

Any idea? Thank you for your help!

**Comment by keijiro** [comment]
Please follow the steps below;

- Remove AmbientOcclusion from the camera.
- Remove AmbientOcclusion.cs and the shaders from the project.
- Re-import MiniEngineAO.unitypackage. https://github.com/keijiro/MiniEngineAO/releases
- Re-add AmbientOcclusion to the camera.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
