### ISSUE TITLE
SSAO fades out when close to screen edge

### ISSUE THREAD

**Issue by LordHelmchen12** [keijiro/MiniEngineAO#6]
Hi there...
awesome SSAO for orthographic cams you got there!
First of all, thanks for sharing!

We run in a little problem with it, maybe we do something wrong or you have an idea how to fix it easy...

When our cam moves away from our walls, at some point near the screen edge the ssao fades out. so all corners light up, wich is very visable and make this effect nearly unusabel for us...

https://drive.google.com/open?id=1bTtlemQEY6EHYlsu4E_7mhHamVM2MuLQ

look at the top corner of this video...

We are using Unity 2018.4+
Orthographic cam:
![grafik](https://user-images.githubusercontent.com/2505595/60019567-73924900-968e-11e9-8f03-6a0dc57cf697.png)

Any Ideas? Did we miss something?

**Comment by keijiro** [comment]
That's a general problem about SSAO; Every SSAO technique has the same issue. You can work around the problem by rendering to a bigger render texture and cropping it to hide the edges, it's not a cost effective solution though.

Please understand that this kind of problem is pretty common in screen space image effects (SSAO, SSR, etc.). If it's not acceptable, I'd recommend looking for other non-screen space techniques.

**Comment by LordHelmchen12** [comment]
Oh wow that was quick...

Dont get me wrong, your system is really awesome and i might sound harder and more rude as i wanted to xD
Yeah i thought that this might be a generall problam of screenspace based calculations.

Is there maybe a way to give your ssao more viewfield over the actual screenspace or has this posteffect only the data rendered from the cam?

I think i will talk to my programming dude if we could try your other solution too. Our game is just a little vertical slice and we dont need to fear performance issues in the moment. game runs smooth.
If you intereseted have a look in the game i could send you a builded version to test :-)

Thanks again for sharing your work and the fast response to my ticket !

**Comment by keijiro** [comment]
By the way, I noticed that you're using Obscurance in the screenshot you provided. This repository is MiniEngineAO -- not Obscurance.

Please clarify if you're actually using MiniEngineAO.

**Comment by LordHelmchen12** [comment]
Oh i think i am in the wrong repo :-(
Sorry my bad, yes we are using obscurance! Feel Free to remove or move this dialoge over.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further problems.
